### ISSUE TITLE
Highland Wars URLs doesn't seem to be working

### ISSUE THREAD

**Issue by tfedor** [Calvein/humble-games#50]
I couldn't find Humble Store widget with Highland Wars anywhere, otherwise I would push commit with fixed URLs. I'm getting 404 here:

http://www.humblebundle.com/store/product/highlandwars?preview=WmTzhzOrZNtS
http://www.humblebundle.com/store/product/highlandwars_tier1?preview=WmTzhzOrZNt
http://www.humblebundle.com/store/product/highlandwars_tier2?preview=WmTzhzOrZNt
http://www.humblebundle.com/store/product/highlandwars_tier3?preview=WmTzhzOrZNt
http://www.humblebundle.com/store/product/highlandwars_tier4?preview=WmTzhzOrZNt
http://www.humblebundle.com/store/product/highlandwars_tier5?preview=WmTzhzOrZNt
http://www.humblebundle.com/store/product/highlandwars_tier6?preview=WmTzhzOrZNt
http://www.humblebundle.com/store/product/highlandwars_tier7?preview=WmTzhzOrZNt

**Comment by ghost** [comment]
The page that contained those widgets is down (http://store.skyrockgames.com/highlandwars/). Since they all were Highland Wars pre-orders, could be that pre-orders are no longer available and thus they've removed the page.
However, if this was the case, I'd find it odd that they announced the Highland Humble store opening (http://www.highlandwars.com/2013/06/highland-wars-humble-store.html) and then they closed it without any notice.

I'd wait a couple of days in case the page comes back online.

**Comment by ghost** [comment]
Browsing PCGamingWiki I've discovered that Highland Wars development has been put on hold, all pre-orders have been refunded and the pre-order page has been taken down: http://highlandwars.skyrockgames.com/forum/viewtopic.php?f=2&t=42

I'll proceed to remove Highland Wars from the games.js file and to close this issue.

**Comment by ghost** [comment]
Highland Wars has been removed from the games list. Issue closed.
